### ISSUE TITLE
SSLCertVerificationError while trying to run experiment againts a remote k8s cluster

### ISSUE THREAD

**Issue by TwinkleTShah** [chaostoolkit/chaostoolkit-kubernetes#98]
Steps:
1. Installed chaostoolkit-kubernetes using ```pip install chaostoolkit-kubernetes``` command on my local windows machine
2. Have a remote kubernetes cluster running.  Added the kube config file pointing to the remote k8s cluster in C:\Users\<xxx>\.kube folder on local machine
3. Verified kube config file by making running "kubectl" commands.
4. Created a simple experiment as shown https://docs.chaostoolkit.org/drivers/kubernetes/#usage
5. Execute chaos run by passing the experiment file.

**Output**:
[2020-09-01 18:52:53 INFO] Validating the experiment's syntax
[2020-09-01 18:52:53 INFO] Experiment looks valid
[2020-09-01 18:52:53 INFO] Running experiment: Do we remain available in face of pod going down?
[2020-09-01 18:52:53 INFO] Steady state hypothesis: Verifying service remains healthy
[2020-09-01 18:52:53 INFO] Probe: all-our-microservices-should-be-healthy
**[2020-09-01 18:52:57 **ERROR**]   => failed: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxxxxxx', port=443): Max retries exceeded with url: /k8s/clusters/xxxxx/apis/apps/v1/namespaces/xxxxx/deployments?fieldSelector=metadata.name%3Dxxxxx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))**
[2020-09-01 18:52:57 WARNING] Probe terminated unexpectedly, so its tolerance could not be validated
[2020-09-01 18:52:57 CRITICAL] Steady state probe 'all-our-microservices-should-be-healthy' is not in the given tolerance so failing this experiment
[2020-09-01 18:52:57 INFO] Experiment ended with status: failed

Can someone help what could be missing?

**Comment by dargmuesli** [comment]
Are you using a self signed certificate? Try to add the last line of the following snippet to your `~/.kube/config`:

```yaml
apiVersion: v1
kind: Config
clusters:
- name: "<my-cluster-name>"
  cluster:
    server: "https://<000.000.000.000>.xip.io/k8s/clusters/<x-x0x0x>"
    certificate-authority-data: "<blablabla>"
    insecure-skip-tls-verify: true
```
